#!/bin/bash

if [ -z "$PYFILE" ]; then
	echo "Error: Env variable \$PYFILE not set."
	exit 1
fi

if [ ! -f "$PYFILE" ]; then
	echo "Error: Python file '$PYFILE' does not exist."
	exit 1
fi

python3 "$PYFILE"
